name = "NeXLDatabase"
uuid = "3a8e364e-c0ba-44cd-b67d-54dc3f0f4eb2"
authors = ["Nicholas W.M. Ritchie <nicholas.wm.ritchie@gmail.com>"]
repo-url = "https://github.com/usnistgov/NeXLDatabase.jl"
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NeXLCore = "93a0284f-3680-435e-8d39-dd6e52a1dbc8"
NeXLMatrixCorrection = "3ab34fdf-2fe8-473b-9b20-30f5809db337"
NeXLSpectrum = "6c578565-ca7f-4012-afc4-b8412d85af92"
NeXLUncertainties = "7127f3d6-1721-46bc-bb38-8fc703dd438e"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Colors = "^0.12.3"
DataFrames = "^0.21.4"
Gadfly = "^1.3.0"
IntervalSets = "^0.5.1"
NeXLCore = "^0.1.0"
NeXLMatrixCorrection = "^0.2.0"
NeXLSpectrum = "^0.2.0"
NeXLUncertainties = "^0.2.0"
PeriodicTable = "^1.0.0"
Reexport = "^0.2.0"
Requires = "^1.0.1"
SQLite = "^1.0.3"
Tables = "^1.0.4"
julia = "^1.5"

[extras]
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test"]
